server:
  port: 8181
spring:
  datasource:
    url: jdbc:mysql://cdb-ql64uem8.cd.tencentcdb.com:10101/postgraduate_forum?useSSL=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
